exclude: ".*/vendor/.*"
repos:
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v4.3.15
      hooks:
          - id: isort
    - repo: https://github.com/ambv/black
      rev: 18.9b0
      hooks:
          - id: black
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.1.0
      hooks:
          - id: check-byte-order-marker
          - id: trailing-whitespace
          - id: mixed-line-ending
            args: ["--fix=lf"]
          - id: check-merge-conflict
          - id: check-json
          - id: check-yaml
          - id: detect-aws-credentials
            args: ["--allow-missing-credentials"]
          - id: detect-private-key
          - id: pretty-format-json
            args: ["--autofix", "--no-sort-keys", "--indent=4"]
    - repo: https://github.com/prettier/prettier
      rev: 1.16.2
      hooks:
          - id: prettier
            files: \.(css|less|scss|ts|tsx|graphql|gql|json|js|jsx|md)$
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v5.14.1
      hooks:
          - id: eslint
            additional_dependencies:
                - eslint@5.8.0
                - eslint-plugin-prettier@3.0.0
                - prettier@1.14.3
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.7.7
      hooks:
          - id: flake8
